### ISSUE TITLE
Error in SQS interface while pushing messages with attributes set in it.

### ISSUE THREAD

**Issue by cristovarghese** [vburenin/firempq#7]
This is the error I encountered in FireMPQ (SQS interface) while pushing messages with message attributes set. Specifically the error occurs where were calculate md5sum of the MessageBody. Seems to disappear if I change the "UnsafeStringToBytes" function in enc/unsafe_cast.go without using the unsafe.Pointer

    `2017/06/15 11:39:31 http: panic serving 172.17.0.1:42020: runtime error: slice bounds out of range
    goroutine 462 [running]:
    net/http.(*conn).serve.func1(0xc420097040)
    	/usr/local/go/src/net/http/server.go:1721 +0xd0
    panic(0x89ad40, 0xb75500)
    	/usr/local/go/src/runtime/panic.go:489 +0x2cf
    crypto/md5.(*digest).Write(0xc4227528b8, 0xc422c941c0, 0x1be, 0xd, 0x20, 0x21e24820, 0xc422752918)
    	/usr/local/go/src/crypto/md5/md5.go:75 +0x1df
    crypto/md5.Sum(0xc422c941c0, 0x1be, 0xd, 0x0, 0x0)
    	/usr/local/go/src/crypto/md5/md5.go:128 +0xd1
    github.com/vburenin/firempq/server/sqsproto/send_message.PushAMessage(0xc4200a49a0, 0xc421e277b0, 0x10, 0xc420132100, 0x8, 0x8, 0xe, 0xc422752be8)
    	/go/src/github.com/vburenin/firempq/server/sqsproto/send_message/send_message.go:225 +0x36d
    github.com/vburenin/firempq/server/sqsproto/send_message.SendMessage(0xc4200a49a0, 0xc420138000, 0x9244d8, 0xb)
    	/go/src/github.com/vburenin/firempq/server/sqsproto/send_message/send_message.go:258 +0x66
    github.com/vburenin/firempq/server/sqsproto.(*SQSRequestHandler).handleQueueActions(0xc42000f418, 0xc4200a49a0, 0xc420138000, 0xb501c0, 0xc4200a49a0)
    	/go/src/github.com/vburenin/firempq/server/sqsproto/sqs_dispatcher.go:60 +0xe1
    github.com/vburenin/firempq/server/sqsproto.(*SQSRequestHandler).dispatchSQSQuery(0xc42000f418, 0xc42000ad00, 0x93f028, 0xc422752cc0)
    	/go/src/github.com/vburenin/firempq/server/sqsproto/sqs_dispatcher.go:114 +0x1ce
    github.com/vburenin/firempq/server/sqsproto.(*SQSRequestHandler).ServeHTTP(0xc42000f418, 0xb4f6c0, 0xc42017a1c0, 0xc42000ad00)
    	/go/src/github.com/vburenin/firempq/server/sqsproto/sqs_dispatcher.go:123 +0x3c
    net/http.(*ServeMux).ServeHTTP(0xc421b3cdb0, 0xb4f6c0, 0xc42017a1c0, 0xc42000ad00)
    	/usr/local/go/src/net/http/server.go:2238 +0x130
    net/http.serverHandler.ServeHTTP(0xc421afb600, 0xb4f6c0, 0xc42017a1c0, 0xc42000ad00)
    	/usr/local/go/src/net/http/server.go:2568 +0x92
    net/http.(*conn).serve(0xc420097040, 0xb4ff40, 0xc422c88280)
    	/usr/local/go/src/net/http/server.go:1825 +0x612
    created by net/http.(*Server).Serve
    	/usr/local/go/src/net/http/server.go:2668 +0x2ce`

**Comment by vburenin** [comment]
Is it sporadic?

**Comment by vburenin** [comment]
Cristo, could you please specify the version of Go you use?

**Comment by vburenin** [comment]
I removed set of unsafe operations, please try again. There is a new version of FMPQ on it's way that will not use unsafe calls. But it is not going to be ready soon.

**Comment by cristovarghese** [comment]
Vlad, No it wasn't sporadic. Go version is go version go1.8.3 linux/amd64.

**Comment by cristovarghese** [comment]
Vlad, No it wasn't sporadic. Go version is go version go1.8.3 linux/amd64.

**Comment by vburenin** [comment]
please try the latest change. I used []byte(val) conversion instead of unsafe operation.

**Comment by cristovarghese** [comment]
That works.. I had that in place already 👍

**Comment by cristovarghese** [comment]
So is it the GC routine causing this issue ?

**Comment by cristovarghese** [comment]
Vlad, No it wasn't sporadic. Go version is go version go1.8.3 linux/amd64.

**Comment by vburenin** [comment]
Hard to say. It is unsafe operation, if that code is not inlined and scheduler switches to another goroutine, bad things may happen.
